# Generated by Django 2.1.14 on 2019-11-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCart', '0002_procategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdTable',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductCatID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='Pictures')),
            ],
        ),
    ]
