# Generated by Django 2.1.14 on 2020-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCart', '0003_prodtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='procategory',
            name='ex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procategory',
            name='ey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procategory',
            name='sx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procategory',
            name='sy',
            field=models.IntegerField(default=0),
        ),
    ]
