# Generated by Django 2.1.14 on 2020-04-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCart', '0004_auto_20200403_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='procategory',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
