# Generated by Django 2.1.14 on 2020-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCart', '0005_procategory_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procategory',
            old_name='location',
            new_name='location_x',
        ),
        migrations.AddField(
            model_name='procategory',
            name='location_y',
            field=models.IntegerField(default=0),
        ),
    ]
